#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG=/etc/tv_limit/nft.sh

load_device() {
    local section="$1"
    local mac
    local enabled
    
    config_get mac "$section" "mac"
    config_get_bool enabled "$section" "enabled" '0'
    
    if [ -n "$mac" ] && [ "$enabled" -eq 1 ]; then
        [ -x "$PROG" ] && "$PROG" add "$mac"
    fi
}

start_service() {
    [ -x "$PROG" ] && "$PROG" start
    
    # Load configuration and apply rules
    config_load "tv_limit"
    config_foreach load_device "device"
}

stop_service() {
    [ -x "$PROG" ] && "$PROG" stop
}

service_triggers() {
    procd_add_reload_trigger "tv_limit"
}

reload_service() {
    stop
    start
}
