#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG=/etc/tv_limit/nft.sh

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" start
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    "$PROG" stop
}

service_running() {
    "$PROG" status
}

reload_service() {
    stop
    start
}